"""Add City and profile.city_id

Revision ID: 46dff0358b8f
Revises: 
Create Date: 2025-12-09 20:55:53.186548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46dff0358b8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_profile_city_id_city', 'city', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profile_city_id_city', type_='foreignkey')
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###
